name: Work 1 Dorx

on:
  push:
    branches:
      - test_1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: echo "Hola Pitaya!"

      - name: Tres impresiones en consola
        run: |
          echo "Impresión 1"
          echo "Impresión 2"
          echo "Impresión 3"
